name: unit
description: A simple tool for conversion between different units of measurement 

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  shared_preferences: any
  launch_review: any
  url_launcher: ^5.7.2
  mailto: ^1.0.0
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - Resources/Strings/en.json
    - Resources/Strings/ru.json
    - Resources/Images/splash.png
    - Resources/Images/logo.png
    - Resources/Images/Measures/BaseUnits/Distance.png
    - Resources/Images/Measures/BaseUnits/Mass.png
    - Resources/Images/Measures/BaseUnits/Time.png
    - Resources/Images/Measures/BaseUnits/Temperature.png
    - Resources/Images/Measures/BaseUnits/ElectricCurrent.png
    - Resources/Images/Measures/BaseUnits/Substance.png
    - Resources/Images/Measures/BaseUnits/Luminous.png

    - Resources/Images/Measures/SpaceAndTime/Acceleration.png
    - Resources/Images/Measures/SpaceAndTime/Area.png
    - Resources/Images/Measures/SpaceAndTime/FuelConsumption.png
    - Resources/Images/Measures/SpaceAndTime/MassFlow.png
    - Resources/Images/Measures/SpaceAndTime/MedicineVolume.png
    - Resources/Images/Measures/SpaceAndTime/PlaneAngle.png
    - Resources/Images/Measures/SpaceAndTime/RotationalSpeed.png
    - Resources/Images/Measures/SpaceAndTime/SpeedVelocity.png
    - Resources/Images/Measures/SpaceAndTime/Volume.png
    - Resources/Images/Measures/SpaceAndTime/VolumetricGasFlow.png
    - Resources/Images/Measures/SpaceAndTime/VolumetricLiquidFlow.png

    - Resources/Images/Measures/ComputerUnits/DataSize.png
    - Resources/Images/Measures/ComputerUnits/DataTransferRate.png
    - Resources/Images/Measures/ComputerUnits/ImageResolution.png

    - Resources/Images/Measures/Magnetism/MagneticField.png
    - Resources/Images/Measures/Magnetism/MagneticFlux.png
    - Resources/Images/Measures/Magnetism/MagneticDensity.png
    - Resources/Images/Measures/Magnetism/ElectricCharge.png
    - Resources/Images/Measures/Magnetism/Resistivity.png
    - Resources/Images/Measures/Magnetism/Conductivity.png

    - Resources/Images/Measures/Light/Illuminance.png
    - Resources/Images/Measures/Light/Luminance.png
    - Resources/Images/Measures/Light/Wavelength.png

    - Resources/Images/Measures/Radiation/AbsorbedDose.png
    - Resources/Images/Measures/Radiation/Activity.png
    - Resources/Images/Measures/Radiation/DoseEquivalent.png
    - Resources/Images/Measures/Radiation/Exposure.png

    - Resources/Images/Measures/Astronomical/AstroLength.png
    - Resources/Images/Measures/Astronomical/AstroMass.png

    - Resources/Images/Measures/Chemistry/HardWater.png
    - Resources/Images/Measures/Chemistry/MassConcentration.png
    - Resources/Images/Measures/Chemistry/MolarMass.png
    - Resources/Images/Measures/Chemistry/MolarVolume.png

    - Resources/Images/Measures/ObsoleteRussian/DistanceOr.png
    - Resources/Images/Measures/ObsoleteRussian/DryVolumeOr.png
    - Resources/Images/Measures/ObsoleteRussian/LiquidVolumeOr.png
    - Resources/Images/Measures/ObsoleteRussian/MassOr.png

    - Resources/Images/Measures/HeatFlowrate/ThermalConductivity.png
    - Resources/Images/Measures/HeatFlowrate/HeatCapacity.png
    - Resources/Images/Measures/HeatFlowrate/HeatOfCombustionMass.png
    - Resources/Images/Measures/HeatFlowrate/HeatOfCombustionVolume.png

    - Resources/Images/Measures/Mechanics/Density.png
    - Resources/Images/Measures/Mechanics/DynamicViscosity.png
    - Resources/Images/Measures/Mechanics/Energy.png
    - Resources/Images/Measures/Mechanics/Force.png
    - Resources/Images/Measures/Mechanics/HighPressure.png
    - Resources/Images/Measures/Mechanics/Inertia.png
    - Resources/Images/Measures/Mechanics/KinematicViscosity.png
    - Resources/Images/Measures/Mechanics/LowPressure.png
    - Resources/Images/Measures/Mechanics/Power.png
    - Resources/Images/Measures/Mechanics/Torque.png


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
